### PR TITLE
Update openapi.yaml with latest swagger-core documentation from server

### PR DESCRIPTION
**Pull request by marco-miller**
This change brings trace-server's [1] version of the TSP OpenApi herein.
It is therefore a continuation of [2]'s WIP.

Contributes to fixing #61 further as yet another incremental step.

[1] https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/189067
[2] https://github.com/theia-ide/trace-server-protocol#alternate-tsp-version

Signed-off-by: Marco Miller <marco.miller@ericsson.com>

### CODE REVIEW

**Comment by marco-miller** [comment]
- This PR should be a rather trivial review despite its size; previous similar ones were.
- Speaking of size, this PR can be reviewed on a per commit basis, at will.
- This PR is a multi-commit one because the corresponding server changes were all merged yesterday (at once; unusual).

**Comment by marco-miller** [comment]
Had to re-push all commits to fix the missing brackets in my Signed-off-by's; sorry, copy-paste mishap.

**Review by PatrickTasse — APPROVED** [review]

**Comment by marco-miller** [comment]
Thanks also to @PatrickTasse for this review.

**Review by MatthewKhouzam — COMMENTED** [review]
Looks great!

**Pull request merged**
